# Generated by Django 5.0.4 on 2024-05-08 09:56

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=150)),
                ("message", models.TextField()),
            ],
        ),
        migrations.AlterModelManagers(
            name="news",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
    ]
