# Generated by Django 5.0.4 on 2024-05-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news_app", "0002_contact_alter_news_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facebook", models.CharField(max_length=100)),
                ("twitter", models.CharField(max_length=100)),
                ("flickr", models.CharField(max_length=100)),
                ("pinterest", models.CharField(max_length=100)),
                ("instagram", models.CharField(max_length=100)),
                ("vimeo", models.CharField(max_length=100)),
                ("youtube", models.CharField(max_length=100)),
                ("mail", models.CharField(max_length=100)),
            ],
        ),
    ]
