# Generated by Django 5.0.4 on 2024-05-09 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news_app", "0003_social"),
    ]

    operations = [
        migrations.RenameField(
            model_name="social",
            old_name="facebook",
            new_name="link",
        ),
        migrations.RenameField(
            model_name="social",
            old_name="flickr",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="social",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="social",
            name="mail",
        ),
        migrations.RemoveField(
            model_name="social",
            name="pinterest",
        ),
        migrations.RemoveField(
            model_name="social",
            name="twitter",
        ),
        migrations.RemoveField(
            model_name="social",
            name="vimeo",
        ),
        migrations.RemoveField(
            model_name="social",
            name="youtube",
        ),
    ]
