# Generated by Django 5.0.4 on 2024-05-11 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news_app", "0004_rename_facebook_social_link_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Social",
        ),
    ]
