# Generated by Django 5.0.4 on 2024-05-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news_app", "0005_delete_social"),
    ]

    operations = [
        migrations.CreateModel(
            name="social_sites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facebook", models.CharField(max_length=100)),
                ("twitter", models.CharField(max_length=100)),
                ("flickr", models.CharField(max_length=100)),
                ("pinterest", models.CharField(max_length=100)),
                ("googleplus", models.CharField(max_length=100)),
                ("vimeo", models.CharField(max_length=100)),
                ("youtube", models.CharField(max_length=100)),
                ("mail", models.CharField(max_length=100)),
            ],
        ),
    ]
