# Generated by Django 5.0.4 on 2024-05-13 05:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news_app", "0006_social_sites"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="social_sites",
            new_name="Social",
        ),
    ]
