# Generated by Django 5.0.4 on 2024-05-20 04:35

import django.db.models.deletion
import django.db.models.manager
import django.views.generic.list
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news_app", "0008_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchResultView",
            fields=[
                (
                    "news_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="news_app.news",
                    ),
                ),
            ],
            bases=(django.views.generic.list.ListView, "news_app.news"),
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="news",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
