# Generated by Django 5.0.4 on 2024-05-20 04:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news_app", "0009_searchresultview_news_view_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="view_count",
        ),
    ]
